apiVersion: 1

policies:
  - orgId: 1
    receiver: email
    group_by:
      - grafana_folder
      - alertname
    group_wait: 10s
    group_interval: 2m
    repeat_interval: 2m
    routes:
      # - receiver: feishu-webhook
      #   object_matchers:
      #     - ["notify", "=", "feishu"]
      #   continue: true # 继续匹配后续策略
      - receiver: email
        object_matchers:
          - ["notify", "=", "feishu"]
        continue: false # 不继续匹配后续策略
